# -*- coding: utf-8 -*-
"""cifar100

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o6WJWmrKnDvQU5lSOPpo-y0ay1TY3sVi

deploy.h5
"""

import streamlit as st
import tensorflow as tf
from PIL import Image, ImageOps
import numpy as np

@st.cache(allow_output_mutation=True, hash_funcs={tf.keras.models.Model: id})
def load_model():
    model = tf.keras.models.load_model('deploy.h5')
    return model

st.write("""
# Cifar 100 Image Classifier
""")

file = st.file_uploader("Choose a cifar 100 photo from your computer", type=["jpg", "png"])

if file is None:
    st.text("Please upload an image file")
else:
    model = load_model()  # Load the model here
    image = Image.open(file)
    st.image(image, use_column_width=True)

    # Move the import_and_predict function here
    def import_and_predict(image_data, model):
        size = (32, 32)
        image = ImageOps.fit(image_data, size, Image.ANTIALIAS)
        img = np.asarray(image)
        img_reshape = img[np.newaxis, ...]
        prediction = model.predict(img_reshape)
        return prediction

    prediction = import_and_predict(image, model)

    class_names = [
        'beaver', 'dolphin', 'otter', 'seal', 'whale', 'aquarium fish', 'flatfish', 'ray', 'shark', 'trout',
        'orchids', 'poppies', 'roses', 'sunflowers', 'tulips', 'bottles', 'bowls', 'cans', 'cups', 'plates',
        'apples', 'mushrooms', 'oranges', 'pears', 'sweet peppers', 'clock', 'computer keyboard', 'lamp', 'telephone', 'television',
        'bed', 'chair', 'couch', 'table', 'wardrobe', 'bee', 'beetle', 'butterfly', 'caterpillar', 'cockroach',
        'bear', 'leopard', 'lion', 'tiger', 'wolf', 'bridge', 'castle', 'house', 'road', 'skyscraper',
        'cloud', 'forest', 'mountain', 'plain', 'sea', 'camel', 'cattle', 'chimpanzee', 'elephant', 'kangaroo',
        'fox', 'porcupine', 'possum', 'raccoon', 'skunk', 'crab', 'lobster', 'snail', 'spider', 'worm',
        'baby', 'boy', 'girl', 'man', 'woman', 'crocodile', 'dinosaur', 'lizard', 'snake', 'turtle',
        'hamster', 'mouse', 'rabbit', 'shrew', 'squirrel', 'maple', 'oak', 'palm', 'pine', 'willow',
        'bicycle', 'bus', 'motorcycle', 'pickup truck', 'train', 'lawn-mower', 'rocket', 'streetcar', 'tank', 'tractor'
    ]

    result = class_names[np.argmax(prediction)]
    st.success("OUTPUT: " + result)